#!/usr/bin/env bash
# Displays all acive IPv4 addresses on the machine.

#! /bin/bash

# saving all the ip addresses
ip_addresses=$(hostname -I)

# splitting them by space
ip_addresses=(${ip_addresses//" "/ })

# Print each ip address line by line

for ip in "${ip_addresses[@]}";
do
  printf "$ip\n"
done
